[project]
name = "nsga2"
version = "0.1.0"
description = "My reproduction of NSGA-II."
readme = "README.md"
authors = [
    { name = "BruceZhang0808", email = "zhangyixiang0808@gmail.com" }
]
requires-python = ">=3.12, <3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pyyaml>=6.0.3",
    "tqdm>=4.70.1",
]

[project.scripts]
nsga2 = "nsga2:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[[tool.uv.index]]
name = "pytorch-cn"
url = "https://mirror.sjtu.edu.cn/pytorch-wheels/cu132"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cn", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }
torchvision = { index = "pytorch-cn", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }
torchaudio = { index = "pytorch-cn", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }