[project]
name = "nsga2"
version = "0.1.0"
description = "My reproduction of NSGA-II."
readme = "README.md"
authors = [
    { name = "BruceZhang0808", email = "zhangyixiang0808@gmail.com" }
]
requires-python = ">=3.12, <3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pyyaml>=6.0.3",
    "tqdm>=4.70.1",
]

[dependency-groups]
dev = ["ipykernel>=7.4.0"]

[project.scripts]
nsga2 = "nsga2.experiments.run_benchmark:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true
